# -*- coding: utf-8 -*-
"""ProyectoIAFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbmsCwF8xZjH2Qm7uV5aWzmGlkhYG2Xn
"""

import pandas as pd

file_path = '/content/Dataset.xlsx'
df = pd.read_excel(file_path)

print(f"Successfully loaded data from {file_path}. Showing the first 5 rows:")
display(df.head())
display(df.info())

df[['ancho_cauce_m',
    'dist_orilla_izq_m',
    'dist_orilla_der_m',
    'prec_mm',
    't_media_C']].describe()

stats_transecto = df.groupby('transecto_id')[
    ['ancho_cauce_m','dist_orilla_izq_m','dist_orilla_der_m']
].agg(['mean','std','min','max'])

stats_transecto

import matplotlib.pyplot as plt

# Histograma ancho
plt.hist(df['ancho_cauce_m'], bins=20)
plt.xlabel('Ancho del cauce (m)')
plt.ylabel('Frecuencia')
plt.title('Distribución de ancho_cauce_m')
plt.show()

# Boxplot por transecto (ancho)
df.boxplot(column='ancho_cauce_m', by='transecto_id', rot=90)
plt.title('Ancho del cauce por transecto')
plt.suptitle('')
plt.xlabel('Transecto')
plt.ylabel('Ancho (m)')
plt.show()

# Crear un índice de tiempo aproximado
df['fecha'] = pd.to_datetime(df['anio'].astype(str) + '-' +
                             df['mes'].astype(str) + '-01')

# Ejemplo: ancho promedio sobre todos los transectos por mes
serie_ancho = df.groupby('fecha')['ancho_cauce_m'].mean()

serie_ancho.plot(marker='o')
plt.ylabel('Ancho medio del cauce (m)')
plt.title('Evolución temporal del ancho medio')
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

# ancho vs precipitación
plt.subplot(1,2,1)
plt.scatter(df['prec_mm'], df['ancho_cauce_m'], alpha=0.6)
plt.xlabel('Precipitación mensual (mm)')
plt.ylabel('Ancho del cauce (m)')
plt.title('Relación entre ancho del cauce y precipitación')

# ancho vs temperatura
plt.subplot(1,2,2)
plt.scatter(df['t_media_C'], df['ancho_cauce_m'], alpha=0.6, color='orange')
plt.xlabel('Temperatura media mensual (°C)')
plt.ylabel('Ancho del cauce (m)')
plt.title('Relación entre ancho del cauce y temperatura')

plt.tight_layout()
plt.show()

"""### Objetivos de modelado

1. Modelo A (principal): predecir el **ancho total del cauce** (`ancho_cauce_m`) a partir de variables climáticas (`prec_mm`, `t_media_C`), temporales (`anio`, `mes`) y espaciales (`transecto_id`).

2. Modelo B (complementario): predecir la **posición/ desplazamiento de la orilla derecha** (`dist_orilla_der_m`) en los transectos ubicados frente al malecón de Puerto Wilches, usando las mismas variables explicativas.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# The dataframe 'df' is already loaded from '/content/Dataset.xlsx' in a previous cell.
# No need to load data again or from a different file 'morfologia_puerto_wilches.csv'.

# Seleccionar solo variables numéricas relevantes
vars_corr = ['ancho_cauce_m',
             'dist_orilla_izq_m',
             'dist_orilla_der_m',
             'prec_mm',
             't_media_C']

corr = df[vars_corr].corr()
print(corr.round(3))

plt.figure(figsize=(8,7)) # Increased figure size for better text visibility
im = plt.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(im, fraction=0.046, pad=0.04)
plt.xticks(range(len(vars_corr)), vars_corr, rotation=45, ha='right')
plt.yticks(range(len(vars_corr)), vars_corr)
plt.title('Matriz de correlación entre variables')

# Add correlation values to the heatmap
for i in range(len(vars_corr)):
    for j in range(len(vars_corr)):
        text = plt.text(j, i, f'{corr.iloc[i, j]:.2f}',
                       ha="center", va="center", color="black", fontsize=10)

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

target_col = 'ancho_cauce_m'
feature_cols = ['anio', 'mes', 'transecto_id', 'prec_mm', 't_media_C']

X = df[feature_cols].values
y = df[target_col].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Escalado para modelos sensibles a escala (SVR)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.metrics import mean_squared_error, r2_score

def evaluar_modelo(nombre, modelo, X_tr, X_te, y_tr, y_te):
    modelo.fit(X_tr, y_tr)
    y_pred = modelo.predict(X_te)
    rmse = np.sqrt(mean_squared_error(y_te, y_pred))
    r2 = r2_score(y_te, y_pred)
    print(f"{nombre} -> RMSE: {rmse:.2f}, R^2: {r2:.3f}")
    return rmse, r2

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

dt = DecisionTreeRegressor(random_state=42)

param_grid_dt = {
    'max_depth': [3, 5, 7, 9, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_dt = GridSearchCV(
    estimator=dt,
    param_grid=param_grid_dt,
    scoring='neg_root_mean_squared_error',  # RMSE (negativo)
    cv=5,
    n_jobs=-1
)

grid_dt.fit(X_train, y_train)

print("Mejores hiperparámetros DT:", grid_dt.best_params_)
print("Mejor RMSE CV (DT):", -grid_dt.best_score_)

# Evaluar en test con el mejor modelo
best_dt = grid_dt.best_estimator_
rmse_dt, r2_dt = evaluar_modelo("DecisionTree (best)", best_dt, X_train, X_test, y_train, y_test)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42, n_jobs=-1)

param_grid_rf = {
    'n_estimators': [100, 200, 500],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_rf = GridSearchCV(
    estimator=rf,
    param_grid=param_grid_rf,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

print("Mejores hiperparámetros RF:", grid_rf.best_params_)
print("Mejor RMSE CV (RF):", -grid_rf.best_score_)

best_rf = grid_rf.best_estimator_
rmse_rf, r2_rf = evaluar_modelo("RandomForest (best)", best_rf, X_train, X_test, y_train, y_test)

from sklearn.svm import SVR

svr = SVR(kernel='rbf')

param_grid_svr = {
    'C': [0.1, 1, 10, 100],
    'epsilon': [0.01, 0.1, 0.5, 1.0],
    'gamma': ['scale', 0.01, 0.1, 1]
}

grid_svr = GridSearchCV(
    estimator=svr,
    param_grid=param_grid_svr,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1
)

grid_svr.fit(X_train_scaled, y_train)

print("Mejores hiperparámetros SVR:", grid_svr.best_params_)
print("Mejor RMSE CV (SVR):", -grid_svr.best_score_)

best_svr = grid_svr.best_estimator_
rmse_svr, r2_svr = evaluar_modelo("SVR (best)", best_svr, X_train_scaled, X_test_scaled, y_train, y_test)

import matplotlib.pyplot as plt
import numpy as np # Ensure numpy is imported for np.arange if not already

resultados = pd.DataFrame({
    'modelo': ['DecisionTree', 'RandomForest', 'SVR'],
    'RMSE_test': [rmse_dt, rmse_rf, rmse_svr],
    'R2_test': [r2_dt, r2_rf, r2_svr]
})

print("Resultados de la evaluación de modelos:")
display(resultados)

# Plotting the comparison
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Bar plot for RMSE
axes[0].bar(resultados['modelo'], resultados['RMSE_test'], color=['skyblue', 'lightcoral', 'lightgreen'])
axes[0].set_title('Comparación de RMSE en el conjunto de prueba')
axes[0].set_ylabel('RMSE')
axes[0].set_xlabel('Modelo')
axes[0].tick_params(axis='x', rotation=45)

# Bar plot for R2 Score
axes[1].bar(resultados['modelo'], resultados['R2_test'], color=['skyblue', 'lightcoral', 'lightgreen'])
axes[1].set_title('Comparación de R2 Score en el conjunto de prueba')
axes[1].set_ylabel('R2 Score')
axes[1].set_xlabel('Modelo')
axes[1].set_ylim(0, 1) # R2 score is typically between 0 and 1
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Predicciones de cada modelo
y_pred_dt  = best_dt.predict(X_test)
y_pred_rf  = best_rf.predict(X_test)
y_pred_svr = best_svr.predict(X_test_scaled)

# Rango común para la diagonal
y_min = min(y_test.min(), y_pred_dt.min(), y_pred_rf.min(), y_pred_svr.min())
y_max = max(y_test.max(), y_pred_dt.max(), y_pred_rf.max(), y_pred_svr.max())
linea = np.linspace(y_min, y_max, 100)

fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharex=True, sharey=True) # Increased figure width for better spacing

# 1. Decision Tree
axes[0].scatter(y_test, y_pred_dt, alpha=0.6)
axes[0].plot(linea, linea, 'r--', label='y = x')
axes[0].set_title('Decision Tree')
axes[0].set_xlabel('Ancho observado (m)')
axes[0].set_ylabel('Ancho predicho (m)') # Added y-label
axes[0].legend()
axes[0].grid(True) # Added grid

# 2. Random Forest
axes[1].scatter(y_test, y_pred_rf, alpha=0.6, color='orange')
axes[1].plot(linea, linea, 'r--', label='y = x')
axes[1].set_title('Random Forest')
axes[1].set_xlabel('Ancho observado (m)')
axes[1].set_ylabel('Ancho predicho (m)') # Added y-label
axes[1].legend()
axes[1].grid(True) # Added grid

# 3. SVR
axes[2].scatter(y_test, y_pred_svr, alpha=0.6, color='green')
axes[2].plot(linea, linea, 'r--', label='y = x')
axes[2].set_title('SVR')
axes[2].set_xlabel('Ancho observado (m)')
axes[2].set_ylabel('Ancho predicho (m)') # Added y-label
axes[2].legend()
axes[2].grid(True) # Added grid

fig.suptitle('Comparación observados vs predichos para cada modelo', y=1.02, fontsize=16) # Increased suptitle font size
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjusted layout to prevent suptitle overlap
plt.show()

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

def metricas_train_test(nombre, modelo, X_tr, X_te, y_tr, y_te):
    y_tr_pred = modelo.predict(X_tr)
    y_te_pred = modelo.predict(X_te)

    rmse_tr = np.sqrt(mean_squared_error(y_tr, y_tr_pred))
    rmse_te = np.sqrt(mean_squared_error(y_te, y_te_pred))

    r2_tr = r2_score(y_tr, y_tr_pred)
    r2_te = r2_score(y_te, y_te_pred)

    print(f"{nombre}")
    print(f"  RMSE train: {rmse_tr:.2f}  |  RMSE test: {rmse_te:.2f}")
    print(f"  R2   train: {r2_tr:.3f}   |  R2   test: {r2_te:.3f}")
    print()

# Decision Tree
metricas_train_test("Decision Tree", best_dt, X_train, X_test, y_train, y_test)

# Random Forest
metricas_train_test("Random Forest", best_rf, X_train, X_test, y_train, y_test)

# SVR (usa datos escalados)
metricas_train_test("SVR", best_svr, X_train_scaled, X_test_scaled, y_train, y_test)

import pandas as pd
import matplotlib.pyplot as plt

importancias = pd.Series(best_rf.feature_importances_, index=feature_cols)
importancias = importancias.sort_values(ascending=True)

plt.figure(figsize=(6,4))
importancias.plot(kind='barh')
plt.xlabel('Importancia relativa')
plt.title('Importancia de variables - Random Forest')
plt.tight_layout()
plt.show()

print(importancias.sort_values(ascending=False))

# ============================================
# RED NEURONAL PARA REGRESIÓN - VERSIÓN RÁPIDA
# Optimizada para probar tiempos en Google Colab
# ============================================

import time
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# --------------------------------------------
# 1. VERIFICAR GPU
# --------------------------------------------
print("TensorFlow version:", tf.__version__)
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# --------------------------------------------
# 2. CARGAR DATOS
# --------------------------------------------
# Ajusta el archivo si tiene otro nombre
df = pd.read_excel(file_path)

# --------------------------------------------
# 3. DEFINIR VARIABLES
# --------------------------------------------
# Usa un conjunto pequeño y coherente de predictores
feature_cols = ['anio', 'mes', 'prec_mm', 't_media_C']
target_col = 'ancho_cauce_m'

X = df[feature_cols].values
y = df[target_col].values

# --------------------------------------------
# 4. TRAIN / TEST SPLIT
# --------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------------------
# 5. ESCALADO
# --------------------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --------------------------------------------
# 6. FUNCIÓN PARA CREAR EL MODELO
# --------------------------------------------
def crear_modelo(n_features,
                 n_hidden=1,
                 n_neurons=32,
                 learning_rate=0.001,
                 dropout_rate=0.0,
                 l2_reg=0.0):

    model = keras.Sequential()
    model.add(layers.Input(shape=(n_features,)))

    for _ in range(n_hidden):
        model.add(
            layers.Dense(
                n_neurons,
                activation='relu',
                kernel_regularizer=regularizers.l2(l2_reg)
            )
        )
        if dropout_rate > 0:
            model.add(layers.Dropout(dropout_rate))

    model.add(layers.Dense(1))  # salida continua

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss='mse',
        metrics=['mae']
    )

    return model

# --------------------------------------------
# 7. REJILLA PEQUEÑA DE HIPERPARÁMETROS
# --------------------------------------------
# Solo 4 configuraciones: rápida para medir tiempo
param_grid = {
    'n_hidden': [2, 3],
    'n_neurons': [32, 64],
    'learning_rate': [0.001],
    'dropout_rate': [0.1, 0.2, 0.3],
    'l2_reg': [0.0, 1e-4],
    'batch_size': [32],
    'epochs': [200]
}

# Total de combinaciones
total_configs = (
    len(param_grid['n_hidden']) *
    len(param_grid['n_neurons']) *
    len(param_grid['learning_rate']) *
    len(param_grid['dropout_rate']) *
    len(param_grid['l2_reg']) *
    len(param_grid['batch_size']) *
    len(param_grid['epochs'])
)

print(f"Total de configuraciones a probar: {total_configs}")

# --------------------------------------------
# 8. BÚSQUEDA DE HIPERPARÁMETROS
# --------------------------------------------
resultados = []
mejor_modelo = None
mejor_config = None
mejor_rmse = np.inf
mejor_history = None

n_features = X_train_scaled.shape[1]

inicio_total = time.time()
contador = 0

for n_hidden in param_grid['n_hidden']:
    for n_neurons in param_grid['n_neurons']:
        for learning_rate in param_grid['learning_rate']:
            for dropout_rate in param_grid['dropout_rate']:
                for l2_reg in param_grid['l2_reg']:
                    for batch_size in param_grid['batch_size']:
                        for epochs in param_grid['epochs']:

                            contador += 1
                            inicio_config = time.time()

                            tf.keras.backend.clear_session()
                            tf.random.set_seed(42)
                            np.random.seed(42)

                            model = crear_modelo(
                                n_features=n_features,
                                n_hidden=n_hidden,
                                n_neurons=n_neurons,
                                learning_rate=learning_rate,
                                dropout_rate=dropout_rate,
                                l2_reg=l2_reg
                            )

                            early_stop = keras.callbacks.EarlyStopping(
                                monitor='val_loss',
                                patience=15,
                                restore_best_weights=True
                            )

                            history = model.fit(
                                X_train_scaled, y_train,
                                validation_split=0.2,
                                epochs=epochs,
                                batch_size=batch_size,
                                verbose=0,
                                callbacks=[early_stop]
                            )

                            y_train_pred = model.predict(X_train_scaled, verbose=0).ravel()
                            y_test_pred = model.predict(X_test_scaled, verbose=0).ravel()

                            rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
                            rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
                            r2_train = r2_score(y_train, y_train_pred)
                            r2_test = r2_score(y_test, y_test_pred)

                            fin_config = time.time()
                            tiempo_config = fin_config - inicio_config

                            resultados.append({
                                'config_num': contador,
                                'n_hidden': n_hidden,
                                'n_neurons': n_neurons,
                                'learning_rate': learning_rate,
                                'dropout_rate': dropout_rate,
                                'l2_reg': l2_reg,
                                'batch_size': batch_size,
                                'epochs_max': epochs,
                                'epochs_real': len(history.history['loss']),
                                'rmse_train': rmse_train,
                                'rmse_test': rmse_test,
                                'r2_train': r2_train,
                                'r2_test': r2_test,
                                'tiempo_seg': tiempo_config
                            })

                            print(f"[{contador}/{total_configs}] "
                                  f"capas={n_hidden}, neuronas={n_neurons}, "
                                  f"dropout={dropout_rate} -> "
                                  f"RMSE test={rmse_test:.2f}, R2 test={r2_test:.3f}, "
                                  f"tiempo={tiempo_config:.1f}s")

                            if rmse_test < mejor_rmse:
                                mejor_rmse = rmse_test
                                mejor_modelo = model
                                mejor_config = {
                                    'n_hidden': n_hidden,
                                    'n_neurons': n_neurons,
                                    'learning_rate': learning_rate,
                                    'dropout_rate': dropout_rate,
                                    'l2_reg': l2_reg,
                                    'batch_size': batch_size,
                                    'epochs_max': epochs
                                }
                                mejor_history = history

fin_total = time.time()
tiempo_total = fin_total - inicio_total

# --------------------------------------------
# 9. RESULTADOS
# --------------------------------------------
resultados_df = pd.DataFrame(resultados).sort_values(by='rmse_test', ascending=True)

print("\n===== MEJORES CONFIGURACIONES =====")
print(resultados_df)

print("\n===== MEJOR CONFIGURACIÓN =====")
print(mejor_config)

print(f"\nTiempo total de búsqueda: {tiempo_total/60:.2f} minutos")

# --------------------------------------------
# 10. EVALUACIÓN FINAL DEL MEJOR MODELO
# --------------------------------------------
y_train_pred_best = mejor_modelo.predict(X_train_scaled, verbose=0).ravel()
y_test_pred_best = mejor_modelo.predict(X_test_scaled, verbose=0).ravel()

rmse_train_best = np.sqrt(mean_squared_error(y_train, y_train_pred_best))
rmse_test_best = np.sqrt(mean_squared_error(y_test, y_test_pred_best))
r2_train_best = r2_score(y_train, y_train_pred_best)
r2_test_best = r2_score(y_test, y_test_pred_best)

print("\n===== DESEMPEÑO FINAL DE LA MEJOR RED =====")
print(f"RMSE train: {rmse_train_best:.2f} | RMSE test: {rmse_test_best:.2f}")
print(f"R2   train: {r2_train_best:.3f} | R2   test: {r2_test_best:.3f}")

# --------------------------------------------
# 11. GRÁFICA DE PÉRDIDA
# --------------------------------------------
plt.figure(figsize=(6,4))
plt.plot(mejor_history.history['loss'], label='Train loss')
plt.plot(mejor_history.history['val_loss'], label='Validation loss')
plt.xlabel('Épocas')
plt.ylabel('MSE')
plt.title('Evolución de pérdida - Mejor red neuronal')
plt.legend()
plt.tight_layout()
plt.show()

# --------------------------------------------
# 12. OBSERVADO VS PREDICHO
# --------------------------------------------
y_min = min(y_test.min(), y_test_pred_best.min())
y_max = max(y_test.max(), y_test_pred_best.max())
linea = np.linspace(y_min, y_max, 100)

plt.figure(figsize=(5,5))
plt.scatter(y_test, y_test_pred_best, alpha=0.6, color='purple')
plt.plot(linea, linea, 'r--', label='y = x')
plt.xlabel('Ancho observado (m)')
plt.ylabel('Ancho predicho (m)')
plt.title('Red neuronal - Observado vs predicho')
plt.legend()
plt.tight_layout()
plt.show()

# --------------------------------------------
# 13. GUARDAR RESULTADOS
# --------------------------------------------
resultados_df.to_csv("resultados_red_neuronal_rapida.csv", index=False)
print("\nArchivo guardado: resultados_red_neuronal_rapida.csv")

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Define feature_cols as used for the Random Forest model (5 features)
rf_feature_cols = ['anio', 'mes', 'transecto_id', 'prec_mm', 't_media_C']
rf_target_col = 'ancho_cauce_m'

# Re-create X for the Random Forest context from the original df
X_rf_full = df[rf_feature_cols].values
y_rf_full = df[rf_target_col].values

# Split data to get X_test_rf, matching the split parameters used for RF training
# Note: y_test itself (for plotting) is assumed to be consistent across splits with same random_state and test_size
_, X_test_rf, _, _ = train_test_split(
    X_rf_full, y_rf_full, test_size=0.2, random_state=42
)

# Ensure prediction variables are defined if this cell is run independently
y_pred_nn = y_test_pred_best # This comes from the NN cell, which used 4 features

# Now use the 5-feature X_test_rf for the Random Forest prediction
y_pred_rf = best_rf.predict(X_test_rf)

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred_rf, alpha=0.6, label='Random Forest', color='tab:blue')
plt.scatter(y_test, y_pred_nn, alpha=0.6, label='Red Neuronal', color='tab:orange')
# línea ideal
min_val = min(y_test.min(), y_pred_rf.min(), y_pred_nn.min())
max_val = max(y_test.max(), y_pred_rf.max(), y_pred_nn.max())
plt.plot([min_val, max_val], [min_val, max_val], 'k--', label='Ideal y=x')

plt.xlabel('Valor observado')
plt.ylabel('Valor predicho')
plt.legend()
plt.title('Ancho del cauce: observado vs predicho (RF vs RN)')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

res_rf = y_test - y_pred_rf
res_nn = y_test - y_pred_nn

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.scatter(y_pred_rf, res_rf, alpha=0.6, color='tab:blue')
plt.axhline(0, color='k', linestyle='--')
plt.xlabel('Predicho RF')
plt.ylabel('Residuo (obs - pred)')
plt.title('Residuos Random Forest')

plt.subplot(1,2,2)
plt.scatter(y_pred_nn, res_nn, alpha=0.6, color='tab:orange')
plt.axhline(0, color='k', linestyle='--')
plt.xlabel('Predicho RN')
plt.ylabel('Residuo (obs - pred)')
plt.title('Residuos Red Neuronal')

plt.tight_layout()
plt.show()

"""**aplicacion de aprendizaje no supervisado**"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score

# Supongamos que df ya está cargado
# Ejemplo: variables numéricas para clustering
vars_cluster = ['ancho_cauce_m', 'dist_orilla_der_m', 'prec_mm', 't_media_C']
X = df[vars_cluster].dropna().values   # elimina filas con NaN

# Estandarizar (muy importante para todos los métodos)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import matplotlib.pyplot as plt

k_values = range(2, 8)   # por ejemplo, de 2 a 7 clusters
inertias = []
silhouettes = []

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=20)
    labels = kmeans.fit_predict(X_scaled)

    inertias.append(kmeans.inertia_)
    sil_score = silhouette_score(X_scaled, labels)
    silhouettes.append(sil_score)
    print(f'k={k}: Inercia={kmeans.inertia_:.2f}, Silhouette={sil_score:.3f}')

# Gráfica método del codo (inercia)
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(k_values, inertias, marker='o')
plt.xlabel('Número de clusters (k)')
plt.ylabel('Inercia (SSE)')
plt.title('Método del codo - KMeans')

# Gráfica coeficiente de silueta
plt.subplot(1,2,2)
plt.plot(k_values, silhouettes, marker='o')
plt.xlabel('Número de clusters (k)')
plt.ylabel('Silhouette')
plt.title('Coeficiente de Silhouette - KMeans')

plt.tight_layout()
plt.show()

k_optimo = 4
kmeans_final = KMeans(n_clusters=k_optimo, random_state=42, n_init=20)
labels_kmeans = kmeans_final.fit_predict(X_scaled)

df_kmeans = df.loc[df[vars_cluster].dropna().index].copy()
df_kmeans['cluster_kmeans'] = labels_kmeans

# Resumen por cluster
resumen_kmeans = df_kmeans.groupby('cluster_kmeans')[vars_cluster].mean()
print(resumen_kmeans)

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the clusters
plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='ancho_cauce_m',
    y='prec_mm',
    hue='cluster_kmeans',
    data=df_kmeans,
    palette='viridis',
    s=100,  # Size of points
    alpha=0.7
)

# Get centroids and inverse transform them
centroids_scaled = kmeans_final.cluster_centers_

# Create a dummy array with the correct number of features for inverse transformation
# Fill with zeros for features not being plotted, and fill with centroid values for the plotted features
# vars_cluster = ['ancho_cauce_m', 'dist_orilla_der_m', 'prec_mm', 't_media_C']
centroid_original_space = scaler.inverse_transform(centroids_scaled)

# Extract relevant centroid coordinates for plotting
idx_ancho = vars_cluster.index('ancho_cauce_m')
idx_prec = vars_cluster.index('prec_mm')

plt.scatter(
    centroid_original_space[:, idx_ancho],
    centroid_original_space[:, idx_prec],
    marker='X', # 'X' for centroids
    s=250, # Larger size for centroids
    color='red',
    edgecolor='black',
    label='Centroides'
)

plt.title(f'Clusters de K-Means (k={k_optimo})')
plt.xlabel('Ancho del Cauce (m)')
plt.ylabel('Precipitación (mm)')
plt.legend(title='Cluster')
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

eps_values = [0.3, 0.5, 0.7, 1.0]      # ajusta si ves que todo queda en un solo cluster o todo en ruido
min_samples_values = [3, 5, 10]

resultados_dbscan = []

for eps in eps_values:
    for min_samples in min_samples_values:
        db = DBSCAN(eps=eps, min_samples=min_samples)
        labels = db.fit_predict(X_scaled)

        # número de clusters (ignorando el ruido -1)
        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        n_ruido = np.sum(labels == -1)

        # silhouette solo tiene sentido si hay al menos 2 clusters válidos
        if n_clusters > 1:
            mask = labels != -1
            sil = silhouette_score(X_scaled[mask], labels[mask])
        else:
            sil = np.nan

        resultados_dbscan.append({
            'eps': eps,
            'min_samples': min_samples,
            'n_clusters': n_clusters,
            'n_ruido': n_ruido,
            'silhouette': sil
        })
        print(f'eps={eps}, min_samples={min_samples} -> clusters={n_clusters}, ruido={n_ruido}, silhouette={sil}')

df_dbscan = pd.DataFrame(resultados_dbscan)
df_dbscan

eps_opt = 0.7
min_samples_opt = 10

db_final = DBSCAN(eps=eps_opt, min_samples=min_samples_opt)
labels_dbscan = db_final.fit_predict(X_scaled)

df_dbscan_labels = df.loc[df[vars_cluster].dropna().index].copy()
df_dbscan_labels['cluster_dbscan'] = labels_dbscan

# Tabla de resumen (sin ruido)
df_dbscan_val = df_dbscan_labels[df_dbscan_labels['cluster_dbscan'] != -1].copy()
resumen_dbscan = df_dbscan_val.groupby('cluster_dbscan')[vars_cluster].mean()
print(resumen_dbscan)

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the DBSCAN clusters
plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='ancho_cauce_m',
    y='prec_mm',
    hue='cluster_dbscan',
    data=df_dbscan_labels, # Use df_dbscan_labels to include noise points (-1)
    palette='viridis', # Choose a suitable palette
    s=100,  # Size of points
    alpha=0.7
)

# Calculate and plot the mean of each cluster as its 'centroid'
# Filter out noise points (-1) before calculating means
clustered_points = df_dbscan_labels[df_dbscan_labels['cluster_dbscan'] != -1]
cluster_means = clustered_points.groupby('cluster_dbscan')[['ancho_cauce_m', 'prec_mm']].mean()

plt.scatter(
    cluster_means['ancho_cauce_m'],
    cluster_means['prec_mm'],
    marker='X', # 'X' for centroids
    s=250, # Larger size for centroids
    color='red',
    edgecolor='black',
    label='Mean Cluster Position'
)

plt.title(f'Clusters de DBSCAN (eps={eps_opt}, min_samples={min_samples_opt}) con Posiciones Medias')
plt.xlabel('Ancho del Cauce (m)')
plt.ylabel('Precipitación (mm)')
plt.legend(title='Cluster')
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.neighbors import NearestNeighbors

k = 10  # min_samples que quieras usar
nn = NearestNeighbors(n_neighbors=k)
nn.fit(X_scaled)
distances, indices = nn.kneighbors(X_scaled)

# Distancia al k-ésimo vecino (última columna)
k_distances = np.sort(distances[:, k-1])

plt.figure(figsize=(8,4))
plt.plot(k_distances)
plt.xlabel('Punto (ordenado)')
plt.ylabel(f'Distancia al {k}-ésimo vecino más cercano')
plt.title('Gráfico k-distancias para elegir eps')
plt.grid(True)
plt.show()

import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from itertools import product

# Exploración de hiperparámetros
n_clusters_values = range(2, 8)   # de 2 a 7 clusters
linkages = ['ward', 'average', 'complete']

resultados_aggl = []

for n_clusters, link in product(n_clusters_values, linkages):
    # ward requiere métrica euclidiana
    if link == 'ward':
        metric = 'euclidean'
    else:
        metric = 'euclidean'  # puedes cambiar a 'manhattan', 'cosine', etc. si quieres

    aggl = AgglomerativeClustering(
        n_clusters=n_clusters,
        linkage=link,
        metric=metric
    )
    labels = aggl.fit_predict(X_scaled)

    sil = silhouette_score(X_scaled, labels)
    resultados_aggl.append({
        'n_clusters': n_clusters,
        'linkage': link,
        'silhouette': sil
    })
    print(f'n_clusters={n_clusters}, linkage={link} -> silhouette={sil:.3f}')

# Pasar a DataFrame para revisar
df_aggl = pd.DataFrame(resultados_aggl)
print('\n=== Tabla de resultados ===')
print(df_aggl.sort_values('silhouette', ascending=False).head(10))

# Ajusta según tu tabla de resultados
n_clusters_opt = 4       # ejemplo
linkage_opt = 'ward'     # ejemplo

aggl_final = AgglomerativeClustering(
    n_clusters=n_clusters_opt,
    linkage=linkage_opt,
    metric='euclidean'
)
labels_aggl = aggl_final.fit_predict(X_scaled)

df_aggl_labels = df.loc[df[vars_cluster].dropna().index].copy()
df_aggl_labels['cluster_aggl'] = labels_aggl

# Resumen de centroides
resumen_aggl = df_aggl_labels.groupby('cluster_aggl')[vars_cluster].mean()
print('\n=== Centroides de los clusters ===')
print(resumen_aggl)

# Silhouette final
sil_final = silhouette_score(X_scaled, labels_aggl)
print(f'\nSilhouette final: {sil_final:.3f}')

# Opcional: gráfica similar a las anteriores
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
scatter = plt.scatter(
    df_aggl_labels['ancho_cauce_m'],
    df_aggl_labels['prec_mm'],
    c=df_aggl_labels['cluster_aggl'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)

# Plotting the centroids
plt.scatter(
    resumen_aggl['ancho_cauce_m'],
    resumen_aggl['prec_mm'],
    marker='X', # 'X' for centroids
    s=250, # Larger size for centroids
    color='red',
    edgecolor='black',
    label='Centroides'
)

plt.xlabel('Ancho del Cauce (m)')
plt.ylabel('Precipitación (mm)')
plt.title(f'Clusters de Agglomerative Clustering (n={n_clusters_opt}, linkage={linkage_opt}) con Centroides')
plt.colorbar(scatter, label='Cluster')
plt.legend(title='Cluster') # Ensure legend shows both clusters and centroids
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# K-means
scatter0 = axes[0].scatter(
    df_kmeans['ancho_cauce_m'],
    df_kmeans['prec_mm'],
    c=df_kmeans['cluster_kmeans'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[0].set_xlabel('Ancho del Cauce (m)')
axes[0].set_ylabel('Precipitación (mm)')
axes[0].set_title('K-means (k=4, silhouette=0.26)')
axes[0].grid(True, alpha=0.3)

# DBSCAN
scatter1 = axes[1].scatter(
    df_dbscan_labels['ancho_cauce_m'],
    df_dbscan_labels['prec_mm'],
    c=df_dbscan_labels['cluster_dbscan'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[1].set_xlabel('Ancho del Cauce (m)')
axes[1].set_ylabel('Precipitación (mm)')
axes[1].set_title('DBSCAN (eps=0.5, min_samples=10, silhouette=0.74*)')
axes[1].grid(True, alpha=0.3)

# Agglomerative
scatter2 = axes[2].scatter(
    df_aggl_labels['ancho_cauce_m'],
    df_aggl_labels['prec_mm'],
    c=df_aggl_labels['cluster_aggl'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[2].set_xlabel('Ancho del Cauce (m)')
axes[2].set_ylabel('Precipitación (mm)')
axes[2].set_title('Agglomerative (n=4, ward, silhouette=0.24)')
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print('* Silhouette de DBSCAN calculado solo sobre puntos no-ruido')

import matplotlib.pyplot as plt
import numpy as np

# Datos de cada método (ajusta según tus resultados finales)
metodos = ['K-means\n(k=4)', 'DBSCAN\n(eps=0.5)', 'Agglomerative\n(n=4, ward)']
silhouette = [0.262, 0.741, 0.237]  # ajusta con tus valores reales
n_clusters = [4, 3, 4]
pct_ruido = [0, 92, 0]  # DBSCAN tiene ruido, los otros no

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

# Silhouette
axes[0].bar(metodos, silhouette, color=['blue', 'orange', 'green'], alpha=0.7)
axes[0].set_ylabel('Coeficiente de Silhouette')
axes[0].set_title('Calidad de separación')
axes[0].set_ylim(0, 1)
axes[0].grid(axis='y', alpha=0.3)

# Número de clusters
axes[1].bar(metodos, n_clusters, color=['blue', 'orange', 'green'], alpha=0.7)
axes[1].set_ylabel('Número de clusters')
axes[1].set_title('Clusters detectados')
axes[1].set_ylim(0, 10)
axes[1].grid(axis='y', alpha=0.3)

# % Ruido
axes[2].bar(metodos, pct_ruido, color=['blue', 'orange', 'green'], alpha=0.7)
axes[2].set_ylabel('% de puntos como ruido')
axes[2].set_title('Cobertura del dataset')
axes[2].set_ylim(0, 100)
axes[2].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Aplicar PCA sobre datos estandarizados
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X_scaled)

# Varianza explicada por cada componente
print('Varianza explicada por cada componente:')
print(pca.explained_variance_ratio_)
print(f'Varianza acumulada PC1+PC2: {pca.explained_variance_ratio_[:2].sum():.2%}')

# Gráfica de varianza explicada
plt.figure(figsize=(8,4))
plt.bar(range(1, 5), pca.explained_variance_ratio_, alpha=0.7)
plt.xlabel('Componente Principal')
plt.ylabel('Proporción de varianza explicada')
plt.title('Varianza explicada por cada componente')
plt.xticks(range(1, 5))
plt.grid(axis='y', alpha=0.3)
plt.show()

# Visualizar datos en PC1 y PC2 coloreados por cluster (p.ej. K-means)
plt.figure(figsize=(8,6))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1],
                     c=df_kmeans['cluster_kmeans'],
                     cmap='viridis', alpha=0.6, edgecolors='k', linewidth=0.3)
plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%} varianza)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%} varianza)')
plt.title('Clusters de K-means en el espacio de Componentes Principales')
plt.colorbar(scatter, label='Cluster')
plt.grid(True, alpha=0.3)
plt.show()

# Loadings: contribución de cada variable a PC1 y PC2
loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
loading_df = pd.DataFrame(
    loadings[:, :2],
    columns=['PC1', 'PC2'],
    index=vars_cluster
)
print('\nContribución de variables a PC1 y PC2:')
print(loading_df)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

# Aplicar t-SNE con perplexity típica
tsne = TSNE(n_components=2, perplexity=30, random_state=42, n_iter=1000, verbose=1)
X_tsne = tsne.fit_transform(X_scaled)

# Crear figura con 3 subplots para comparar PCA, t-SNE y original
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Panel 1: Espacio original (ancho vs precipitación) con clusters de K-means
scatter0 = axes[0].scatter(
    df_kmeans['ancho_cauce_m'],
    df_kmeans['prec_mm'],
    c=df_kmeans['cluster_kmeans'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[0].set_xlabel('Ancho del Cauce (m)')
axes[0].set_ylabel('Precipitación (mm)')
axes[0].set_title('Espacio original (ancho vs precipitación)')
axes[0].grid(True, alpha=0.3)

# Panel 2: Espacio PCA (PC1 vs PC2)
scatter1 = axes[1].scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=df_kmeans['cluster_kmeans'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[1].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%} varianza)')
axes[1].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%} varianza)')
axes[1].set_title('Espacio PCA (reducción lineal)')
axes[1].grid(True, alpha=0.3)

# Panel 3: Espacio t-SNE
scatter2 = axes[2].scatter(
    X_tsne[:, 0],
    X_tsne[:, 1],
    c=df_kmeans['cluster_kmeans'],
    cmap='viridis',
    alpha=0.6,
    edgecolors='k',
    linewidth=0.3
)
axes[2].set_xlabel('t-SNE dimensión 1')
axes[2].set_ylabel('t-SNE dimensión 2')
axes[2].set_title('Espacio t-SNE (reducción no lineal)')
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(f'\nNota: Los tres paneles muestran los mismos datos coloreados por cluster de K-means')
print(f'PCA captura {pca.explained_variance_ratio_[:2].sum():.1%} de varianza en 2D')
print(f't-SNE preserva vecindades locales (perplexity={tsne.perplexity})')